language: python

install:
  - pip install -r requirements.txt

jobs:
  include:
    - language: python
      python: 3.8
      install: 
      - pip install -r requirements.txt
      script:
      - pytest -v ./src/*_tests.py

    - language: node_js
      node_js: 12
      install:
      - npm install
      script:
      - npm run build
  
